//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS.AFP.Framework {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DS.AFP.Framework.Spring.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BootstrapperRunCompleted 的本地化字符串。
        /// </summary>
        internal static string BootstrapperRunCompleted {
            get {
                return ResourceManager.GetString("BootstrapperRunCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfigureContainerBegin 的本地化字符串。
        /// </summary>
        internal static string ConfigureContainerBegin {
            get {
                return ResourceManager.GetString("ConfigureContainerBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfigureContainerEnd 的本地化字符串。
        /// </summary>
        internal static string ConfigureContainerEnd {
            get {
                return ResourceManager.GetString("ConfigureContainerEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfiguringModuleCatalogBegin 的本地化字符串。
        /// </summary>
        internal static string ConfiguringModuleCatalogBegin {
            get {
                return ResourceManager.GetString("ConfiguringModuleCatalogBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfiguringModuleCatalogEnd 的本地化字符串。
        /// </summary>
        internal static string ConfiguringModuleCatalogEnd {
            get {
                return ResourceManager.GetString("ConfiguringModuleCatalogEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfiguringServiceLocatorSingletonBegin 的本地化字符串。
        /// </summary>
        internal static string ConfiguringServiceLocatorSingletonBegin {
            get {
                return ResourceManager.GetString("ConfiguringServiceLocatorSingletonBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfiguringServiceLocatorSingletonEnd 的本地化字符串。
        /// </summary>
        internal static string ConfiguringServiceLocatorSingletonEnd {
            get {
                return ResourceManager.GetString("ConfiguringServiceLocatorSingletonEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfiguringSpringContainerBegin 的本地化字符串。
        /// </summary>
        internal static string ConfiguringSpringContainerBegin {
            get {
                return ResourceManager.GetString("ConfiguringSpringContainerBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfiguringSpringContainerEnd 的本地化字符串。
        /// </summary>
        internal static string ConfiguringSpringContainerEnd {
            get {
                return ResourceManager.GetString("ConfiguringSpringContainerEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContainerInitializeException 的本地化字符串。
        /// </summary>
        internal static string ContainerInitializeException {
            get {
                return ResourceManager.GetString("ContainerInitializeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatingModuleCatalogBegin 的本地化字符串。
        /// </summary>
        internal static string CreatingModuleCatalogBegin {
            get {
                return ResourceManager.GetString("CreatingModuleCatalogBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatingModuleCatalogEnd 的本地化字符串。
        /// </summary>
        internal static string CreatingModuleCatalogEnd {
            get {
                return ResourceManager.GetString("CreatingModuleCatalogEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatingSpringContainerBegin 的本地化字符串。
        /// </summary>
        internal static string CreatingSpringContainerBegin {
            get {
                return ResourceManager.GetString("CreatingSpringContainerBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatingSpringContainerEnd 的本地化字符串。
        /// </summary>
        internal static string CreatingSpringContainerEnd {
            get {
                return ResourceManager.GetString("CreatingSpringContainerEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializingModulesBegin 的本地化字符串。
        /// </summary>
        internal static string InitializingModulesBegin {
            get {
                return ResourceManager.GetString("InitializingModulesBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializingModulesEnd 的本地化字符串。
        /// </summary>
        internal static string InitializingModulesEnd {
            get {
                return ResourceManager.GetString("InitializingModulesEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志创建成功 的本地化字符串。
        /// </summary>
        internal static string LoggerCreatedSuccessfully {
            get {
                return ResourceManager.GetString("LoggerCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日志异常 的本地化字符串。
        /// </summary>
        internal static string NullLoggerFacadeException {
            get {
                return ResourceManager.GetString("NullLoggerFacadeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModuleCatalog为空异常 的本地化字符串。
        /// </summary>
        internal static string NullModuleCatalogException {
            get {
                return ResourceManager.GetString("NullModuleCatalogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NullUnityContainerException 的本地化字符串。
        /// </summary>
        internal static string NullUnityContainerException {
            get {
                return ResourceManager.GetString("NullUnityContainerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PreInitializeModulesBegin 的本地化字符串。
        /// </summary>
        internal static string PreInitializeModulesBegin {
            get {
                return ResourceManager.GetString("PreInitializeModulesBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PreInitializeModulesEnd 的本地化字符串。
        /// </summary>
        internal static string PreInitializeModulesEnd {
            get {
                return ResourceManager.GetString("PreInitializeModulesEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegisteringFrameworkExceptionTypesBegin 的本地化字符串。
        /// </summary>
        internal static string RegisteringFrameworkExceptionTypesBegin {
            get {
                return ResourceManager.GetString("RegisteringFrameworkExceptionTypesBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegisteringFrameworkExceptionTypesEnd 的本地化字符串。
        /// </summary>
        internal static string RegisteringFrameworkExceptionTypesEnd {
            get {
                return ResourceManager.GetString("RegisteringFrameworkExceptionTypesEnd", resourceCulture);
            }
        }
    }
}
