//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS.AFP.Framework.WPF {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DS.AFP.Framework.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 适配器类型无效 的本地化字符串。
        /// </summary>
        internal static string AdapterInvalidTypeException {
            get {
                return ResourceManager.GetString("AdapterInvalidTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引导程序运行完成 的本地化字符串。
        /// </summary>
        internal static string BootstrapperRunCompleted {
            get {
                return ResourceManager.GetString("BootstrapperRunCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法改变的区域名称的异常 的本地化字符串。
        /// </summary>
        internal static string CannotChangeRegionNameException {
            get {
                return ResourceManager.GetString("CannotChangeRegionNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法创建导航目标 的本地化字符串。
        /// </summary>
        internal static string CannotCreateNavigationTarget {
            get {
                return ResourceManager.GetString("CannotCreateNavigationTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法注册复合命令本身 的本地化字符串。
        /// </summary>
        internal static string CannotRegisterCompositeCommandInItself {
            get {
                return ResourceManager.GetString("CannotRegisterCompositeCommandInItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法注册两次相同的命令 的本地化字符串。
        /// </summary>
        internal static string CannotRegisterSameCommandTwice {
            get {
                return ResourceManager.GetString("CannotRegisterSameCommandTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能添加类型继承从区域的行为 的本地化字符串。
        /// </summary>
        internal static string CanOnlyAddTypesThatInheritIFromRegionBehavior {
            get {
                return ResourceManager.GetString("CanOnlyAddTypesThatInheritIFromRegionBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置容器开始 的本地化字符串。
        /// </summary>
        internal static string ConfigureContainerBegin {
            get {
                return ResourceManager.GetString("ConfigureContainerBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置容器结束 的本地化字符串。
        /// </summary>
        internal static string ConfigureContainerEnd {
            get {
                return ResourceManager.GetString("ConfigureContainerEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置默认区域的行为开始 的本地化字符串。
        /// </summary>
        internal static string ConfigureDefaultRegionBehaviorsBegin {
            get {
                return ResourceManager.GetString("ConfigureDefaultRegionBehaviorsBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置默认区域的行为结束 的本地化字符串。
        /// </summary>
        internal static string ConfigureDefaultRegionBehaviorsEnd {
            get {
                return ResourceManager.GetString("ConfigureDefaultRegionBehaviorsEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置适配器映射区域开始 的本地化字符串。
        /// </summary>
        internal static string ConfigureRegionAdapterMappingsBegin {
            get {
                return ResourceManager.GetString("ConfigureRegionAdapterMappingsBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置适配器映射区域结束 的本地化字符串。
        /// </summary>
        internal static string ConfigureRegionAdapterMappingsEnd {
            get {
                return ResourceManager.GetString("ConfigureRegionAdapterMappingsEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置模块目录开始 的本地化字符串。
        /// </summary>
        internal static string ConfiguringModuleCatalogBegin {
            get {
                return ResourceManager.GetString("ConfiguringModuleCatalogBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置模块目录结束 的本地化字符串。
        /// </summary>
        internal static string ConfiguringModuleCatalogEnd {
            get {
                return ResourceManager.GetString("ConfiguringModuleCatalogEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置服务定位器子女开始 的本地化字符串。
        /// </summary>
        internal static string ConfiguringServiceLocatorSingletonBegin {
            get {
                return ResourceManager.GetString("ConfiguringServiceLocatorSingletonBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfiguringServiceLocatorSingletonEnd 的本地化字符串。
        /// </summary>
        internal static string ConfiguringServiceLocatorSingletonEnd {
            get {
                return ResourceManager.GetString("ConfiguringServiceLocatorSingletonEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfiguringSpringContainerBegin 的本地化字符串。
        /// </summary>
        internal static string ConfiguringSpringContainerBegin {
            get {
                return ResourceManager.GetString("ConfiguringSpringContainerBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfiguringSpringContainerEnd 的本地化字符串。
        /// </summary>
        internal static string ConfiguringSpringContainerEnd {
            get {
                return ResourceManager.GetString("ConfiguringSpringContainerEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContainerInitializeException 的本地化字符串。
        /// </summary>
        internal static string ContainerInitializeException {
            get {
                return ResourceManager.GetString("ContainerInitializeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContentControlHasContentException 的本地化字符串。
        /// </summary>
        internal static string ContentControlHasContentException {
            get {
                return ResourceManager.GetString("ContentControlHasContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatingModuleCatalogBegin 的本地化字符串。
        /// </summary>
        internal static string CreatingModuleCatalogBegin {
            get {
                return ResourceManager.GetString("CreatingModuleCatalogBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatingModuleCatalogEnd 的本地化字符串。
        /// </summary>
        internal static string CreatingModuleCatalogEnd {
            get {
                return ResourceManager.GetString("CreatingModuleCatalogEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatingSpringContainerBegin 的本地化字符串。
        /// </summary>
        internal static string CreatingSpringContainerBegin {
            get {
                return ResourceManager.GetString("CreatingSpringContainerBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatingSpringContainerEnd 的本地化字符串。
        /// </summary>
        internal static string CreatingSpringContainerEnd {
            get {
                return ResourceManager.GetString("CreatingSpringContainerEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeactiveNotPossibleException 的本地化字符串。
        /// </summary>
        internal static string DeactiveNotPossibleException {
            get {
                return ResourceManager.GetString("DeactiveNotPossibleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeactiveNotPossibleException 的本地化字符串。
        /// </summary>
        internal static string DelegateCommandDelegatesCannDeactiveNotPossibleException {
            get {
                return ResourceManager.GetString("DelegateCommandDelegatesCannDeactiveNotPossibleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DelegateCommandDelegatesCannotBeNull 的本地化字符串。
        /// </summary>
        internal static string DelegateCommandDelegatesCannotBeNull {
            get {
                return ResourceManager.GetString("DelegateCommandDelegatesCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DelegateCommandInvalidGenericPayloadType 的本地化字符串。
        /// </summary>
        internal static string DelegateCommandInvalidGenericPayloadType {
            get {
                return ResourceManager.GetString("DelegateCommandInvalidGenericPayloadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HostControlCannotBeSetAfterAttach 的本地化字符串。
        /// </summary>
        internal static string HostControlCannotBeSetAfterAttach {
            get {
                return ResourceManager.GetString("HostControlCannotBeSetAfterAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializingModulesBegin 的本地化字符串。
        /// </summary>
        internal static string InitializingModulesBegin {
            get {
                return ResourceManager.GetString("InitializingModulesBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializingModulesEnd 的本地化字符串。
        /// </summary>
        internal static string InitializingModulesEnd {
            get {
                return ResourceManager.GetString("InitializingModulesEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemsControlHasItemsSourceException 的本地化字符串。
        /// </summary>
        internal static string ItemsControlHasItemsSourceException {
            get {
                return ResourceManager.GetString("ItemsControlHasItemsSourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志创建成功 的本地化字符串。
        /// </summary>
        internal static string LoggerCreatedSuccessfully {
            get {
                return ResourceManager.GetString("LoggerCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MappingExistsException 的本地化字符串。
        /// </summary>
        internal static string MappingExistsException {
            get {
                return ResourceManager.GetString("MappingExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NavigationServiceHasNoRegion 的本地化字符串。
        /// </summary>
        internal static string NavigationServiceHasNoRegion {
            get {
                return ResourceManager.GetString("NavigationServiceHasNoRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoRegionAdapterException 的本地化字符串。
        /// </summary>
        internal static string NoRegionAdapterException {
            get {
                return ResourceManager.GetString("NoRegionAdapterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日志异常 的本地化字符串。
        /// </summary>
        internal static string NullLoggerFacadeException {
            get {
                return ResourceManager.GetString("NullLoggerFacadeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModuleCatalog为空异常 的本地化字符串。
        /// </summary>
        internal static string NullModuleCatalogException {
            get {
                return ResourceManager.GetString("NullModuleCatalogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NullUnityContainerException 的本地化字符串。
        /// </summary>
        internal static string NullUnityContainerException {
            get {
                return ResourceManager.GetString("NullUnityContainerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnViewRegisteredException 的本地化字符串。
        /// </summary>
        internal static string OnViewRegisteredException {
            get {
                return ResourceManager.GetString("OnViewRegisteredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PreInitializeModulesBegin 的本地化字符串。
        /// </summary>
        internal static string PreInitializeModulesBegin {
            get {
                return ResourceManager.GetString("PreInitializeModulesBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PreInitializeModulesEnd 的本地化字符串。
        /// </summary>
        internal static string PreInitializeModulesEnd {
            get {
                return ResourceManager.GetString("PreInitializeModulesEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegionBehaviorAttachCannotBeCallWithNullRegion 的本地化字符串。
        /// </summary>
        internal static string RegionBehaviorAttachCannotBeCallWithNullRegion {
            get {
                return ResourceManager.GetString("RegionBehaviorAttachCannotBeCallWithNullRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegionBehaviorRegionCannotBeSetAfterAttach 的本地化字符串。
        /// </summary>
        internal static string RegionBehaviorRegionCannotBeSetAfterAttach {
            get {
                return ResourceManager.GetString("RegionBehaviorRegionCannotBeSetAfterAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegionCreationException 的本地化字符串。
        /// </summary>
        internal static string RegionCreationException {
            get {
                return ResourceManager.GetString("RegionCreationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegionManagerWithDifferentNameException 的本地化字符串。
        /// </summary>
        internal static string RegionManagerWithDifferentNameException {
            get {
                return ResourceManager.GetString("RegionManagerWithDifferentNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegionNameCannotBeEmptyException 的本地化字符串。
        /// </summary>
        internal static string RegionNameCannotBeEmptyException {
            get {
                return ResourceManager.GetString("RegionNameCannotBeEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegionNameExistsException 的本地化字符串。
        /// </summary>
        internal static string RegionNameExistsException {
            get {
                return ResourceManager.GetString("RegionNameExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegionNotFound 的本地化字符串。
        /// </summary>
        internal static string RegionNotFound {
            get {
                return ResourceManager.GetString("RegionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegionNotInRegionManagerException 的本地化字符串。
        /// </summary>
        internal static string RegionNotInRegionManagerException {
            get {
                return ResourceManager.GetString("RegionNotInRegionManagerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegionViewExistsException 的本地化字符串。
        /// </summary>
        internal static string RegionViewExistsException {
            get {
                return ResourceManager.GetString("RegionViewExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegionViewNameExistsException 的本地化字符串。
        /// </summary>
        internal static string RegionViewNameExistsException {
            get {
                return ResourceManager.GetString("RegionViewNameExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegisteringFrameworkExceptionTypesBegin 的本地化字符串。
        /// </summary>
        internal static string RegisteringFrameworkExceptionTypesBegin {
            get {
                return ResourceManager.GetString("RegisteringFrameworkExceptionTypesBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegisteringFrameworkExceptionTypesEnd 的本地化字符串。
        /// </summary>
        internal static string RegisteringFrameworkExceptionTypesEnd {
            get {
                return ResourceManager.GetString("RegisteringFrameworkExceptionTypesEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StringCannotBeNullOrEmpty 的本地化字符串。
        /// </summary>
        internal static string StringCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TypeWithKeyNotRegistered 的本地化字符串。
        /// </summary>
        internal static string TypeWithKeyNotRegistered {
            get {
                return ResourceManager.GetString("TypeWithKeyNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpdateRegionException 的本地化字符串。
        /// </summary>
        internal static string UpdateRegionException {
            get {
                return ResourceManager.GetString("UpdateRegionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ViewNotInRegionException 的本地化字符串。
        /// </summary>
        internal static string ViewNotInRegionException {
            get {
                return ResourceManager.GetString("ViewNotInRegionException", resourceCulture);
            }
        }
    }
}
